"""Consumer program that processes outputs generated by the producer.

This program continuously monitors the queue and processes files as they become available.
"""

import argparse
import gc
import sys
import time
import traceback
from pathlib import Path
from typing import Optional, Dict, Any

import torch
import yaml

# Add project root to path to enable imports
project_root = Path(__file__).parent.parent.parent

from src.detector import Detector
from src.model_loader import ModelLoader
from src.queue_manager import QueueManager


def load_config(config_path: Optional[str] = None) -> Dict[str, Any]:
    """
    Load configuration from YAML file.
    
    Args:
        config_path: Path to config file. If None, uses conf_predict.yaml in project root.
        
    Returns:
        Dictionary containing configuration values with defaults.
    """
    # if not YAML_AVAILABLE:
    #     return _get_default_config()
    
    if config_path is None:
        config_path = project_root / "conf_predict.yaml"
    else:
        config_path = Path(config_path)
    
    if not config_path.exists():
        print(f"Warning: Config file not found: {config_path}")
        print("Using default configuration")
        return _get_default_config()
    
    try:
        with open(config_path, 'r', encoding='utf-8') as f:
            config = yaml.safe_load(f) or {}
        
        # Merge with defaults to ensure all keys exist
        default_config = _get_default_config()
        return _merge_config(default_config, config)
    except Exception as e:
        print(f"Error loading config file {config_path}: {e}")
        print("Using default configuration")
        return _get_default_config()


def _get_default_config() -> Dict[str, Any]:
    """Get default configuration values."""
    return {
        'model': {
            'local_path': None,
            'model_variant': 'training',
            'force_download': False
        },
        'detection': {
            'confidence_threshold': 0.25,
            'iou_threshold': 0.45,
            'image_size': 640
        },
        'paths': {
            'input_dir': 'data/input_test',
            'output_dir': 'data/output',
            'image_extensions': ['.tif', '.TIF', '.tiff', '.TIFF', 
                                '.png', '.PNG', 
                                '.jpg', '.JPG', '.jpeg', '.JPEG',
                                '.bmp', '.BMP',
                                '.webp', '.WEBP']
        },
        'queue': {
            'db_path': 'output_queue.db',
            'poll_interval': 1.0,
            'max_unprocessed': 10,
            'cleanup_on_exit': True
        },
        'output': {
            'save': True,
            'save_visualization': True,
            'delete_after_processing': True
        },
        'processing': {
            'standalone_mode': False,
            'continue_on_error': True,
            'verbose': True
        }
    }


def _merge_config(default: Dict[str, Any], user: Dict[str, Any]) -> Dict[str, Any]:
    """Recursively merge user config into default config."""
    result = default.copy()
    for key, value in user.items():
        if key in result and isinstance(result[key], dict) and isinstance(value, dict):
            result[key] = _merge_config(result[key], value)
        else:
            result[key] = value
    return result


def main_predict(
    image_path: str,
    detector: Detector,
    config: Optional[Dict[str, Any]] = None,
    imgsz: Optional[int] = None,
    output_dir: Optional[str] = None,
    verbose: Optional[bool] = None
) -> bool:
    """
    Predict objects in a single image using YOLO model.
    
    This function integrates the prediction logic from predict_example.py
    for processing individual images in the consumer queue.
    
    Args:
        image_path: Path to the image file to process
        detector: Pre-initialized Detector instance (reused for all images)
        config: Configuration dictionary (if None, loads from conf_predict.yaml)
        imgsz: Input image size (overrides config if provided)
        output_dir: Output directory (overrides config if provided)
        verbose: Print detailed summaries (overrides config if provided)
        
    Returns:
        True if processing was successful, False otherwise
    """
    # Load config if not provided
    if config is None:
        config = load_config()
    
    # Use provided values or fall back to config
    imgsz = imgsz if imgsz is not None else config['detection']['image_size']
    output_dir = output_dir or config['paths']['output_dir']
    verbose = verbose if verbose is not None else config['processing']['verbose']
    save_visualization = config['output']['save_visualization']
    
    image_path_obj = Path(image_path)
    
    if not image_path_obj.exists():
        print(f"Warning: Image file does not exist: {image_path}")
        return False
    
    try:
        # Check if file is a supported image format
        supported_extensions = set(config['paths']['image_extensions'])
        
        if image_path_obj.suffix not in supported_extensions:
            print(f"Warning: Unsupported image format: {image_path_obj.suffix}")
            return False
        
        # Process the image
        if verbose:
            print(f"Processing: {image_path_obj.name}")
        
        result = detector.detect(
            image_path=image_path_obj,
            imgsz=imgsz,
            save=config['output']['save'],
            save_dir=output_dir,
            augment=True,
            visualize=False,
        )
        
        if result:
            # Get summary
            summary = detector.get_detections_summary(result)
            if verbose:
                print(f"Detection Summary:")
                print(f"  Number of objects: {summary['num_detections']}")
                print(f"  Average confidence: {summary['average_confidence']:.3f}")
            
            # Visualize if enabled
            if save_visualization:
                # Use .tif extension for georeferenced TIF images, .jpg for others
                if image_path_obj.suffix.lower() in ['.tif', '.tiff']:
                    output_path = Path(output_dir) / f"{image_path_obj.stem}_detections.tif"
                else:
                    output_path = Path(output_dir) / f"{image_path_obj.stem}_detections.jpg"
                detector.visualize(image_path_obj, result, output_path)
                if verbose:
                    print(f"  Output saved to: {output_path}")
        
        if verbose:
            print(f"Successfully processed: {image_path}")
        return True
        
    except Exception as e:
        print(f"Error processing {image_path}: {e}")
        if verbose:
            traceback.print_exc()
        return False
    finally:
        # Clean up memory after processing each image
        gc.collect()
        
        # Clear GPU cache if CUDA is available
        if torch.cuda.is_available():
            torch.cuda.empty_cache()


def process_file(file_path: str, detector: Detector, **kwargs) -> bool:
    """
    Process a single output file using the prediction logic.
    
    Args:
        file_path: Path to the file to process
        detector: Pre-initialized Detector instance
        **kwargs: Additional arguments passed to main_predict
        
    Returns:
        True if processing was successful, False otherwise
    """
    return main_predict(file_path, detector, **kwargs)


def main(
    config_path: Optional[str] = None,
    queue_db_path: Optional[str] = None,
    poll_interval: Optional[float] = None,
    cleanup_on_exit: Optional[bool] = None,
    model_path: Optional[str] = None,
    conf_threshold: Optional[float] = None,
    imgsz: Optional[int] = None,
    output_dir: Optional[str] = None,
    standalone_mode: Optional[bool] = None,
    verbose: Optional[bool] = None
):
    """
    Main consumer function.
    
    Args:
        config_path: Path to config file (default: conf_predict.yaml)
        queue_db_path: Path to queue database file (overrides config if provided)
        poll_interval: Seconds to wait between queue checks (overrides config if provided)
        cleanup_on_exit: Remove entries for missing files on exit (overrides config if provided)
        model_path: Path to local model file (overrides config if provided)
        conf_threshold: Confidence threshold (overrides config if provided)
        imgsz: Input image size (overrides config if provided)
        output_dir: Output directory (overrides config if provided)
        standalone_mode: Run in standalone mode (overrides config if provided)
        verbose: Print detailed output (overrides config if provided)
    """
    # Load configuration
    config = load_config(config_path)
    
    # Use provided arguments or fall back to config values
    queue_db_path = queue_db_path or config['queue']['db_path']
    poll_interval = poll_interval if poll_interval is not None else config['queue']['poll_interval']
    cleanup_on_exit = cleanup_on_exit if cleanup_on_exit is not None else config['queue']['cleanup_on_exit']
    output_dir = output_dir or config['paths']['output_dir']
    verbose = verbose if verbose is not None else config['processing']['verbose']
    
    # Load model once and reuse for all images (major performance improvement)
    if verbose:
        print("Loading model (this may take a moment)...")
    
    loader = ModelLoader()
    model_path_config = model_path or config['model']['local_path']
    conf_threshold_config = conf_threshold if conf_threshold is not None else config['detection']['confidence_threshold']
    iou_threshold_config = config['detection']['iou_threshold']
    
    try:
        if model_path_config:
            model = loader.load_model(local_path=model_path_config)
        else:
            # Use model variant from config
            model_variant = config['model']['model_variant']
            force_download = config['model']['force_download']
            model = loader.load_model(
                model_variant=model_variant,
                force_download=force_download
            )
        
        # Initialize detector once and reuse for all images
        detector = Detector(
            model, 
            conf_threshold=conf_threshold_config,
            iou_threshold=iou_threshold_config
        )
        
        if verbose:
            print("Model loaded successfully!\n")
    except Exception as e:
        print(f"Error loading model: {e}")
        if verbose:
            traceback.print_exc()
        return
    
    # Determine if we should use standalone mode
    use_standalone = standalone_mode if standalone_mode is not None else config['processing']['standalone_mode']
    
    if use_standalone:
        # Standalone mode: process files directly from a directory
        if verbose:
            print("Running in standalone mode")
            print(f"Processing all images in {config['paths']['input_dir']} directory\n")
        
        input_dir = Path(config['paths']['input_dir'])
        if not input_dir.exists():
            print(f"Error: Input directory does not exist: {input_dir}")
            return
        
        # Find all image files using config extensions
        image_files = []
        for ext in config['paths']['image_extensions']:
            # Convert .ext to *.ext for glob
            glob_pattern = f"*{ext}"
            image_files.extend(input_dir.glob(glob_pattern))
        
        image_files = list(set(image_files))
        image_files.sort()
        
        if not image_files:
            print(f"No image files found in {input_dir}")
            return
        
        if verbose:
            print(f"Found {len(image_files)} image file(s) to process\n")
        
        continue_on_error = config['processing']['continue_on_error']
        
        for idx, image_path in enumerate(image_files, 1):
            if verbose:
                print(f"\n[{idx}/{len(image_files)}] Processing: {image_path.name}")
                print("-" * 60)
            
            try:
                success = main_predict(
                    str(image_path),
                    detector=detector,
                    config=config,
                    imgsz=imgsz,
                    output_dir=output_dir,
                    verbose=verbose
                )
                
                if not success:
                    print(f"Failed to process: {image_path}")
                    if not continue_on_error:
                        print("Stopping due to error (continue_on_error=False)")
                        break
            except Exception as e:
                print(f"Error processing {image_path}: {e}")
                if verbose:
                    traceback.print_exc()
                if not continue_on_error:
                    print("Stopping due to error (continue_on_error=False)")
                    break
        
        if verbose:
            print(f"\n{'=' * 60}")
            print(f"Processing complete! Processed {len(image_files)} file(s).")
            print(f"{'=' * 60}")
        return
    
    # Initialize queue manager
    max_unprocessed = config['queue']['max_unprocessed']
    delete_after = config['output']['delete_after_processing']
    continue_on_error = config['processing']['continue_on_error']
    
    queue_manager = QueueManager(db_path=queue_db_path, max_unprocessed=max_unprocessed)
    if verbose:
        print(f"Consumer started (polling every {poll_interval}s)")
        print("Press Ctrl+C to stop\n")
    
    try:
        while True:
            # Get next pending file
            file_path = queue_manager.get_next_pending()
            
            if file_path is None:
                # No pending files, wait and check again
                time.sleep(poll_interval)
                continue
            
            # Mark as processing to prevent other consumers from picking it up
            if not queue_manager.mark_processing(file_path):
                # File was already taken by another consumer or removed
                continue
            
            # Process the file using prediction logic
            success = main_predict(
                file_path,
                detector=detector,
                config=config,
                imgsz=imgsz,
                output_dir=output_dir,
                verbose=verbose
            )
            
            if success:
                # Mark as completed and remove from queue
                queue_manager.mark_completed(file_path)
                
                # Delete the processed file if configured
                if delete_after:
                    try:
                        Path(file_path).unlink()
                        if verbose:
                            print(f"Deleted processed file: {file_path}\n")
                    except Exception as e:
                        print(f"Warning: Could not delete file {file_path}: {e}\n")
            else:
                # Processing failed
                if continue_on_error:
                    if verbose:
                        print(f"Processing failed for {file_path}, removing from queue\n")
                    queue_manager.mark_completed(file_path)
                else:
                    print(f"Processing failed for {file_path}, keeping in queue (status: processing)\n")
                    # Leave it as processing so it won't be picked up again
                    # Note: This will block the file from being processed by other consumers
            
    except KeyboardInterrupt:
        if verbose:
            print("\nConsumer stopped by user")
    except Exception as e:
        print(f"Error in consumer: {e}")
        if verbose:
            traceback.print_exc()
    finally:
        if cleanup_on_exit:
            if verbose:
                print("Cleaning up missing file entries...")
            queue_manager.cleanup_missing_files()
        if verbose:
            print("Consumer exited")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Consumer program for processing outputs with object detection",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Use default config file (conf_predict.yaml)
  python -m src.consumer
  
  # Use custom config file
  python -m src.consumer --config my_config.yaml
  
  # Override config values via command line
  python -m src.consumer --conf 0.3 --imgsz 960 --model-path model.pt
  
  # Run in standalone mode
  python -m src.consumer --standalone
        """
    )
    parser.add_argument(
        "--config",
        type=str,
        default=None,
        help="Path to config file (default: conf_predict.yaml)"
    )
    parser.add_argument(
        "--queue-db",
        type=str,
        default=None,
        help="Path to queue database file (overrides config)"
    )
    parser.add_argument(
        "--poll-interval",
        type=float,
        default=None,
        help="Seconds to wait between queue checks (overrides config)"
    )
    parser.add_argument(
        "--no-cleanup",
        action="store_true",
        help="Don't cleanup missing file entries on exit (overrides config)"
    )
    parser.add_argument(
        "--model-path",
        type=str,
        default=None,
        help="Path to local model file (overrides config)"
    )
    parser.add_argument(
        "--conf",
        type=float,
        default=None,
        help="Confidence threshold for detections (overrides config)"
    )
    parser.add_argument(
        "--imgsz",
        type=int,
        default=None,
        choices=[640, 960, 1280],
        help="Input image size (overrides config)"
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default=None,
        help="Directory to save detection results (overrides config)"
    )
    parser.add_argument(
        "--standalone",
        action="store_true",
        help="Run in standalone mode (process all images in input_dir)"
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="Reduce output verbosity"
    )
    
    args = parser.parse_args()
    
    main(
        config_path=args.config,
        queue_db_path=args.queue_db,
        poll_interval=args.poll_interval,
        cleanup_on_exit=False if args.no_cleanup else None,
        model_path=args.model_path,
        conf_threshold=args.conf,
        imgsz=args.imgsz,
        output_dir=args.output_dir,
        standalone_mode=True if args.standalone else None,
        verbose=False if args.quiet else None
    )

